apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ncote

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jupyterhub-custom-templates
    files:
      - page.html=templates/page.html
      - login.html=templates/login.html
      - spawn.html=templates/spawn.html
  
  - name: jupyterhub-custom-static-css
    files:
      - style.css=static/css/style.css