apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ncote

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: jupyterhub-custom-templates
    files:
      - native-login.html=customization/templates/native-login.html
      - spawn.html=customization/templates/spawn.html
  
  - name: jupyterhub-custom-static-css
    files:
      - style.css=customization/static/css/style.css